title: Rocco Marosi
sector: Architectural Photography
long-title: Rocco Marosi Architectural Photography
email: rocco.marosi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Rocco Marosi and I specialize in Architectural Photography Services.
keywords: photographer, architecture, architectural photography, get a quote, specialized, professional, skilled, images, villa, resort, mall, public spaces, available.
license: https://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US
version: 0.4.1

baseurl: ""
url: "https://roccomarosi.com"

github:
  username: toybreaker
twitter:
  username: rokmatwit
google:
  analytics: UA-43130984-1
linkedin: https://www.linkedin.com/in/roccomarosi
instagram: https://www.instagram.com/rocco.marosi

# for jekyll-seo-tag
social:
  name: Rocco Marosi
  links:
    - https://www.linkedin.com/in/roccomarosi
    - https://www.instagram.com/rocco.marosi/

# Build settings
markdown: kramdown
plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap
 - html-proofer
exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSEÃŸ
 - gulpfile.js
 - package.json
 - DS_Store
 - Icon
 - node_modules
 - .workinprogress
permalink: pretty


collections:
  pages:
   output: true
   permalink: /:path/
